name: Bug report
description: File a bug report
labels: [bug]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What happened?
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Reproduction steps
      description: How to reproduce the issue
  - type: input
    id: version
    attributes:
      label: Version/Commit
  - type: textarea
    id: logs
    attributes:
      label: Logs
